/**
 * Application route definitions and consolidated Power Hubs navigation metadata
 */

export const PRIMARY_HUBS = [
  {
    id: 'observability',
    label: 'Plant Observability',
    path: '/dashboard',
    iconName: 'LayoutDashboard',
    tag: 'Vitals & Energy',
    description: 'Executive KPIs, emissions, peer benchmark & circularity',
    subItems: [
      { label: 'Overview', path: '/dashboard' },
      { label: 'Emissions', path: '/emissions' },
      { label: 'Benchmark', path: '/benchmark' },
      { label: 'Circularity', path: '/circularity' },
      { label: 'Data Ingestion', path: '/data-upload' },
      { label: 'Facility Setup', path: '/facility' },
    ],
  },
  {
    id: 'leaks',
    label: 'Leak Forensics & Solutions',
    path: '/leaks',
    iconName: 'AlertTriangle',
    tag: 'Anomalies & Why?',
    description: 'Carbon anomalies, root cause diagnosis & certified interventions',
    badge: 'Flagged',
    subItems: [
      { label: 'Incident Registry', path: '/leaks' },
      { label: 'BEE Interventions', path: '/recommendations' },
    ],
  },
  {
    id: 'strategy',
    label: 'Decarbonization Sandbox',
    path: '/simulation',
    iconName: 'Sliders',
    tag: 'Simulation & Plan',
    description: 'Interactive What-If simulation, Gantt deployment & 2030 SBTi curve',
    subItems: [
      { label: 'What-If Sim', path: '/simulation' },
      { label: 'Action Planner', path: '/action-planner' },
      { label: '5-Year Trajectory', path: '/trajectory' },
    ],
  },
  {
    id: 'compliance',
    label: 'Compliance Vault',
    path: '/audit-report',
    iconName: 'FileText',
    tag: 'ISO 14064 / BRSR',
    description: 'Auditor-grade ESG disclosure packs & SHA-256 cryptographic provenance',
    subItems: [
      { label: 'Audit Pack Export', path: '/audit-report' },
    ],
  },
];

export const NAV_ITEMS = [
  {
    id: 'strategy-hub',
    label: 'Decarbonization Sandbox',
    path: '/strategy',
    iconName: 'Sliders',
    description: 'Unified simulation, Gantt roadmap, and SBTi trajectory studio',
    group: 'projection',
  },
  {
    id: 'dashboard',
    label: 'Executive Dashboard',
    path: '/dashboard',
    iconName: 'LayoutDashboard',
    description: 'Overview of emissions, top leaks, and savings opportunity',
    group: 'primary',
  },
  {
    id: 'facility',
    label: 'Facility Setup',
    path: '/facility',
    iconName: 'Building2',
    description: 'Plant parameters, operational shifts, and equipment',
    group: 'primary',
  },
  {
    id: 'data-upload',
    label: 'Data Ingestion',
    path: '/data-upload',
    iconName: 'UploadCloud',
    description: 'Process CSV upload and verification',
    group: 'primary',
  },
  {
    id: 'emissions',
    label: 'Emission Intelligence',
    path: '/emissions',
    iconName: 'Activity',
    description: 'Energy sources, processes, equipment breakdown',
    group: 'analytics',
  },
  {
    id: 'leaks',
    label: 'Carbon Leak Points',
    path: '/leaks',
    iconName: 'AlertTriangle',
    description: 'Ranked leak anomalies and deviation scores',
    badge: 'Flagged',
    group: 'analytics',
  },
  {
    id: 'recommendations',
    label: 'Circular Alternatives',
    path: '/recommendations',
    iconName: 'Sparkles',
    description: 'Engineering interventions & Capex/Opex payback',
    group: 'solutions',
  },
  {
    id: 'action-planner',
    label: 'Action Planner',
    path: '/action-planner',
    iconName: 'ListChecks',
    description: 'Phased implementation priority (Immediate to Long Term)',
    group: 'solutions',
  },
  {
    id: 'simulation',
    label: 'What-If Simulator',
    path: '/simulation',
    iconName: 'Sliders',
    description: 'Interactive intervention modeling & scenario comparison',
    group: 'projection',
  },
  {
    id: 'trajectory',
    label: '5-Year Trajectory',
    path: '/trajectory',
    iconName: 'TrendingDown',
    description: '2026-2030 BAU vs Decarbonization pathway',
    group: 'projection',
  },
  {
    id: 'benchmark',
    label: 'Industry Benchmark',
    path: '/benchmark',
    iconName: 'BarChart3',
    description: 'Intensity comparison vs sector average & peer cluster',
    group: 'intelligence',
  },
  {
    id: 'circularity',
    label: 'Circularity Index',
    path: '/circularity',
    iconName: 'RefreshCw',
    description: '0-100 score across 5 circularity pillars',
    group: 'intelligence',
  },
  {
    id: 'audit-report',
    label: 'Audit Report',
    path: '/audit-report',
    iconName: 'FileText',
    description: 'Industrial consulting memorandum & export actions',
    group: 'intelligence',
  },
];
